name: Vulnerability comparison

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scan-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "ubuntu:latest"
          - "python:3"
          - "python:3-slim"
          - "mcr.microsoft.com/vscode/devcontainers/python:3"
          - "gcr.io/google.com/cloudsdktool/google-cloud-cli:latest"
          - "hashicorp/terraform:latest"
          - "ghcr.io/brabster/terraform-bootstrap-gcp:latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install osv-scanner
        run: sudo ./scripts/install_osv_scanner.sh

      - name: Scan image
        id: scan
        run: ./research/scan_image.sh ${{ matrix.image }}

      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.scan.outputs.artifact_name_prefix }}
          path: |
            ${{ steps.scan.outputs.sarif_path }}
            ${{ steps.scan.outputs.metadata_path }}

  generate-report:
    runs-on: ubuntu-latest
    needs: scan-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download scan artifacts
        uses: actions/download-artifact@v4
        with:
          path: uncommitted/
          pattern: scan-output-*
          merge-multiple: true

      - name: Generate report
        run: ./research/generate_report.sh
      
      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability_comparison
          path: uncommitted/vulnerabilities_comparison.md
